"""
Kokoro TTS — Sage English Audio Generator
Stories 3–7: 乔晚的第二局 / 宋知夏的反转 / 谢无忧的零度 / 问药 / 陆清眠读你

60 chapters · ~200 vocab per story · 854 unique words total

Usage:
    python kokoro_generate.py

Output:
    audio/<word>.mp3   (854 files, one per unique vocab word)

Requirements:
    pip install kokoro-onnx soundfile numpy
    Download from https://github.com/thewh1teagle/kokoro-onnx/releases:
        kokoro-v0_19.onnx   (model weights)
        voices.json          (voice embeddings)
    Place both files in the same directory as this script.

Notes:
    - Voice: af_sarah (clear American English, good for vocabulary learning)
    - Speed: 0.85 (slightly slower for clarity)
    - File names match the app af() function:
        word.toLowerCase().replace(/\\s+/g,'_').replace(/[^a-z0-9_-]/gi,'')
    - Already-generated files are skipped — safe to re-run after interruptions
"""

import os, re

VOICE = "af_sarah"
SPEED = 0.85

WORDS = [
    'abandon',
    'abrupt',
    'absorb',
    'acceptance',
    'access',
    'acclimate',
    'accomplice',
    'accountability',
    'accumulate',
    'accumulated',
    'accurate',
    'accustom',
    'accustomed',
    'acknowledgement',
    'acquiesce',
    'acute',
    'adjust',
    'administer',
    'administrative',
    'afford',
    'affordable',
    'affront',
    'afraid',
    'agitation',
    'ajar',
    'alarm',
    'alarmed',
    'allegation',
    'allege',
    'allocation',
    'ally',
    'alternate',
    'amass',
    'amateur',
    'amber',
    'analysis',
    'annotation',
    'anomaly',
    'anonymity',
    'anonymous',
    'anticipate',
    'anxiety',
    'appeal',
    'applaud',
    'appreciation',
    'apprehension',
    'appropriate',
    'approval',
    'archaeology',
    'archive',
    'archivist',
    'armour',
    'assessment',
    'asset',
    'assign',
    'assume',
    'atmospheric',
    'attain',
    'atypical',
    'audacious',
    'audience',
    'audit',
    'auditable',
    'audition',
    'aura',
    'austere',
    'authentic',
    'authorize',
    'available',
    'background noise',
    'backup',
    'banal',
    'bear',
    'bearing',
    'belonging',
    'benefit',
    'betray',
    'bias',
    'black',
    'blacklist',
    'blackmail',
    'bland',
    'block',
    'bloom',
    'bluntly',
    'botanical',
    'boulevard',
    'brave',
    'breach',
    'breakthrough',
    'brew',
    'bribe',
    'brief',
    'briefing',
    'briefing room',
    'brighten',
    'brim',
    'brittle',
    'broadcast',
    'bud',
    'build rapport',
    'build up',
    'bypass',
    'calculate',
    'calculated',
    'calculus',
    'candid',
    'capitulate',
    'career',
    'case file',
    'casting',
    'casual',
    'casual conversation',
    'catalogue',
    'cautious',
    'celebratory',
    'celebrity',
    'ceremonial',
    'challenge',
    'charge',
    'charming',
    'checkpoint',
    'chuckle',
    'circulate',
    'civilian',
    'clarify',
    'clarity',
    'clause',
    'clinical',
    'co-write',
    'coercive',
    'cognitive',
    'collapse',
    'comfortable',
    'commentary',
    'commit',
    'commonplace',
    'compartmentalise',
    'compatible',
    'compendium',
    'competence',
    'competent',
    'compile',
    'complain',
    'completion',
    'complex',
    'complicated',
    'compose',
    'comprehend',
    'compromise',
    'compulsion',
    'concede',
    'concentrated',
    'concise',
    'conclude',
    'conduct',
    'conduit',
    'confess',
    'confide',
    'confirm',
    'confound',
    'confront',
    'confrontation',
    'confrontational',
    'connect',
    'consistent',
    'consolation',
    'consolidate',
    'conspire',
    'constitution',
    'construct',
    'consult',
    'consultant',
    'consultation',
    'consume',
    'contaminate',
    'contingency',
    'contradictory',
    'contraindication',
    'convenience',
    'conventional',
    'convey',
    'convince',
    'coordinator',
    'cordon',
    'correct',
    'cost',
    'courtesy',
    'cowardly',
    'create',
    'credential',
    'credit',
    'criminal',
    'criteria',
    'critique',
    'cross-reference',
    'crowded',
    'crucial',
    'crumble',
    'crystallise',
    'crystallize',
    'cumulative',
    'curate',
    'curiosity',
    'curious',
    'curl',
    'curriculum vitae',
    'custodian',
    'daylight',
    'debrief',
    'decent',
    'decision',
    'decline',
    'deduce',
    'default',
    'defensive',
    'definitive',
    'deft',
    'deliberate',
    'demeanour',
    'deployment',
    'deposition',
    'derivative',
    'designation',
    'desolate',
    'desperate',
    'detach',
    'detached',
    'detail',
    'detain',
    'detect',
    'deteriorate',
    'determine',
    'deviate',
    'diagnosis',
    'diagnostic',
    'dietary',
    'digest',
    'dignity',
    'dilemma',
    'direct',
    'direction',
    'disclose',
    'discomfort',
    'discreet',
    'discrepancy',
    'disguise',
    'dishonest',
    'dismantle',
    'disorientation',
    'dispassionate',
    'distinct',
    'distinguish',
    'disturb',
    'documentary',
    'dominance',
    'domineer',
    'donation',
    'dosage',
    'drag',
    'drag on',
    'drifter',
    'drive',
    'dubbing',
    'dubious',
    'eager',
    'ease',
    'echo',
    'economical',
    'edition',
    'eerie',
    'effective',
    'effortless',
    'eloquent',
    'embed',
    'embody',
    'emerge',
    'emit',
    'empathy',
    'empirical',
    'endorse',
    'endure',
    'engrave',
    'enquire',
    'entourage',
    'envisage',
    'envision',
    'epicentre',
    'erroneous',
    'erupt',
    'escalate',
    'eunuch',
    'evacuate',
    'evasion',
    'even',
    'even-toned',
    'evidence',
    'exact',
    'exaggerate',
    'examination',
    'exceptional',
    'excessive',
    'exchange',
    'exempt',
    'exhausted',
    'exile',
    'existence',
    'expendable',
    'exploit',
    'expose',
    'exposed',
    'expound',
    'express',
    'extraordinary',
    'fabricated',
    'facade',
    'faded',
    'fair',
    'falsify',
    'familiar',
    'fever',
    'figure out',
    'fitting',
    'fixation',
    'flat',
    'flaw',
    'flicker',
    'followup',
    'forceful',
    'forecast',
    'forensic',
    'foresee',
    'formal',
    'formidable',
    'foundation',
    'foundational',
    'fracture',
    'fragrance',
    'frame',
    'freeze',
    'frostbite',
    'function',
    'gauge',
    'generator',
    'genre',
    'genuine',
    'genuinely',
    'gesture',
    'gloat',
    'glow',
    'grasp',
    'graveyard shift',
    'gravity',
    'grip',
    'groundwork',
    'habit',
    'habitual',
    'harm',
    'hasten',
    'hear',
    'hedge',
    'heed',
    'heroic',
    'hesitate',
    'hierarchy',
    'high-functioning',
    'highlight',
    'hinder',
    'hoard',
    'hoarse',
    'hold',
    'horizon',
    'hover',
    'human',
    'humour',
    'hypothesis',
    'identical',
    'ignite',
    'immaculate',
    'impact',
    'impartial',
    'imperial',
    'implicated',
    'implication',
    'imprint',
    'impulsive',
    'inclination',
    'inconsistency',
    'incorporate',
    'indirect',
    'indistinct',
    'infected',
    'infer',
    'inference',
    'inhabit',
    'initiate',
    'inject',
    'innocence',
    'innocent',
    'inquiry',
    'inscribe',
    'inscrutable',
    'insidious',
    'insignia',
    'instinct',
    'instruction',
    'insubordination',
    'integrity',
    'intelligence',
    'intense',
    'intent',
    'interact',
    'interaction',
    'interest',
    'intermittent',
    'intern',
    'internal',
    'interpretation',
    'interrogation',
    'interrupt',
    'intimacy',
    'intricate',
    'intuitive',
    'inventory',
    'involuntary',
    'ironic',
    'irregularity',
    'irrevocable',
    'isolated',
    'issue',
    'jealousy',
    'journal',
    'judgement',
    'jurisdiction',
    'labour',
    'landscape',
    'laugh softly',
    'layered',
    'lead investigator',
    'lean',
    'lecture',
    'lethargic',
    'level',
    'liability',
    'lieutenant',
    'limit',
    'linger',
    'listen',
    'litigation',
    'live',
    'locate',
    'location scouting',
    'lock away',
    'lockdown',
    'logic',
    'loneliness',
    'longing',
    'loophole',
    'low',
    'lucid',
    'mandate',
    'manifest',
    'manipulate',
    'manuscript',
    'mask',
    'measured',
    'mechanics',
    'mechanism',
    'memorandum',
    'memorial',
    'memorize',
    'mend',
    'merger',
    'method',
    'methodical',
    'methodically',
    'mild',
    'mimic',
    'misconception',
    'moment',
    'monitor',
    'morale',
    'motivation',
    'mourn',
    'mundane',
    'mutant',
    'muted',
    'naive',
    'nameless',
    'nappendix',
    'nausea',
    'ndecode',
    'neglect',
    'negotiate',
    'negotiation',
    'neutral',
    'neutralize',
    'newcomer',
    'newsletter',
    'noise',
    'nominate',
    'nonchalant',
    'nostalgia',
    'notation',
    'notch',
    'note',
    'notebook',
    'notorious',
    'numb',
    'objectivity',
    'oblique',
    'obscure',
    'obscurity',
    'observation',
    'observe',
    'obsess',
    'obsessive',
    'open',
    'option',
    'ordinary',
    'organised',
    'orient',
    'original',
    'originate',
    'outbreak',
    'outline',
    'overextend',
    'override',
    'oversimplify',
    'owe',
    'packaged',
    'pale',
    'pan',
    'panic',
    'paradox',
    'paralysis',
    'particular',
    'passive',
    'patrol',
    'pattern',
    'pattern recognition',
    'pause',
    'peace',
    'peculiar',
    'penetrate',
    'perceptive',
    'perform',
    'perimeter',
    'peripheral',
    'periphery',
    'perpetually',
    'personal',
    'petition',
    'pharmaceutical',
    'pioneer',
    'pity',
    'plausible',
    'playback',
    'plea',
    'pocket',
    'ponder',
    'pore over',
    'portfolio',
    'portray',
    'portrayal',
    'possessive',
    'potential',
    'practical',
    'pragmatic',
    'precedent',
    'precise',
    'precision',
    'preface',
    'preference',
    'premeditated',
    'premier',
    'premise',
    'preparation',
    'prepared',
    'present',
    'pressure',
    'prestigious',
    'previous',
    'prior',
    'private',
    'privilege',
    'probe',
    'procurement',
    'productive',
    'professional',
    'proficient',
    'profile',
    'profiling',
    'proof',
    'prosecution',
    'protect',
    'protection',
    'protocol',
    'proud',
    'provocation',
    'prudent',
    'pry',
    'psychological assessment',
    'public',
    'publicize',
    'pull back',
    'punish',
    'pursue',
    'quality',
    'quarters',
    'query',
    'quiet',
    'quip',
    'radiate',
    'random',
    'ration',
    'rationale',
    'real-world',
    'reasoning',
    'rebuild',
    'reclaim',
    'recognise',
    'recognition',
    'record',
    'recover',
    'recuse',
    'refine',
    'regard',
    'register',
    'regular',
    'rehearse',
    'reinforced',
    'reinstate',
    'relaxed',
    'relay',
    'relief',
    'reluctant',
    'rely',
    'remain',
    'remarkably',
    'remedy',
    'remit',
    'remorseful',
    'remote',
    'renowned',
    'repair',
    'repeat',
    'replay',
    'report',
    'repress',
    'reprieve',
    'request',
    'resentful',
    'reserve',
    'resignation',
    'resigned',
    'resilient',
    'resolution',
    'resolve',
    'resource',
    'responsibility',
    'responsible',
    'restitution',
    'restore',
    'restrain',
    'restriction',
    'resume',
    'retaliate',
    'retract',
    'retreat',
    'retrieve',
    'return',
    'returned',
    'revenge',
    'review',
    'revision',
    'revival',
    'right',
    'rival',
    'routine',
    'rumour',
    'rundown',
    'rupture',
    'sanction',
    'savings',
    'scandalous',
    'scheme',
    'scope',
    'script',
    'scrutinise',
    'scrutinize',
    'seal',
    'sealed',
    'seamlessly',
    'see through',
    'seek',
    'seminar',
    'sensation',
    'sense',
    'sequential',
    'serene',
    'serial',
    'session',
    'settle',
    'shadowy',
    'shelter',
    'shield',
    'shift',
    'shimmer',
    'shock',
    'sidelined',
    'siege',
    'sigh out',
    'signal',
    'simultaneously',
    'sincere',
    'singular',
    'size up',
    'sketch',
    'slip out',
    'smoke',
    'soften',
    'solidarity',
    'sorrow',
    'space',
    'sparse',
    'specific',
    'specifically',
    'specify',
    'specimen',
    'spontaneity',
    'spread',
    'stabilise',
    'stability',
    'stabilize',
    'stand by',
    'standout',
    'startling',
    'state',
    'stay',
    'steady',
    'sterile',
    'still',
    'stipend',
    'stir',
    'stocked',
    'storyline',
    'stray',
    'stringent',
    'structured',
    'subdued',
    'submerge',
    'submit',
    'subordinate',
    'subscribe',
    'subside',
    'substantial',
    'substantiate',
    'subtle',
    'sudden',
    'suffocate',
    'summons',
    'superior',
    'superstition',
    'supplement',
    'surface',
    'surreal',
    'surrender',
    'surveillance',
    'survey',
    'suspend',
    'sustain',
    'symposium',
    'systematic',
    'systematically',
    'tap',
    'target',
    'tedious',
    'temperature',
    'template',
    'tender',
    'tentatively',
    'testimony',
    'theoretical',
    'thesis',
    'threat',
    'tighten',
    'title',
    'toast',
    'tolerant',
    'tolerate',
    'toneless',
    'toxic',
    'toxicity',
    'trace back',
    'traceable',
    'training',
    'transform',
    'translucent',
    'transmit',
    'transparent',
    'treatise',
    'triumph',
    'trophy',
    'trust',
    'tutored',
    'unattributed',
    'uncomfortable',
    'unconscious',
    'uncover',
    'underestimate',
    'undermine',
    'underrepresented',
    'unease',
    'unfiltered',
    'unguarded',
    'uniform',
    'unleash',
    'unlock',
    'unnerve',
    'unprejudiced',
    'unravel',
    'unresolved',
    'unsheathe',
    'update',
    'urban',
    'username',
    'vacancy',
    'validation',
    'validity',
    'vegetation',
    'verbalise',
    'vertigo',
    'victim',
    'vigilant',
    'viral',
    'visceral',
    'visible',
    'void',
    'voluntary',
    'wall',
    'wander',
    'warm',
    'warmer',
    'waver',
    'weary',
    'weigh',
    'weight',
    'whisper',
    'wholeness',
    'willing',
    'wilt',
    'withdraw',
    'yield',
]


def word_to_filename(word):
    """Match the app's af() function exactly."""
    s = word.lower()
    s = re.sub(r'\\s+', '_', s)
    s = re.sub(r'[^a-z0-9_-]', '', s)
    return s + ".mp3"


def main():
    try:
        from kokoro_onnx import Kokoro
    except ImportError:
        print("ERROR: kokoro-onnx not installed.")
        print("Run: pip install kokoro-onnx soundfile numpy")
        return

    script_dir  = os.path.dirname(os.path.abspath(__file__))
    model_path  = os.path.join(script_dir, "kokoro-v0_19.onnx")
    voices_path = os.path.join(script_dir, "voices.json")

    for p in (model_path, voices_path):
        if not os.path.exists(p):
            print(f"ERROR: File not found: {p}")
            print("Download: https://github.com/thewh1teagle/kokoro-onnx/releases")
            return

    print("Loading Kokoro model...")
    kokoro = Kokoro(model_path, voices_path)

    output_dir = os.path.join(script_dir, "audio")
    os.makedirs(output_dir, exist_ok=True)

    total = len(WORDS)
    print(f"Voice: {VOICE}  |  Speed: {SPEED}  |  Output: audio/  |  Words: {total}\n")

    skipped = generated = 0
    errors = []

    for i, word in enumerate(WORDS, 1):
        filename = word_to_filename(word)
        filepath = os.path.join(output_dir, filename)

        if os.path.exists(filepath):
            print(f"[{i:4}/{total}] SKIP  {word}")
            skipped += 1
            continue

        try:
            import soundfile as sf
            samples, sample_rate = kokoro.create(word, voice=VOICE, speed=SPEED, lang="en-us")
            sf.write(filepath, samples, sample_rate)
            print(f"[{i:4}/{total}] OK    {word}  ->  {filename}")
            generated += 1
        except Exception as e:
            print(f"[{i:4}/{total}] ERROR {word}: {e}")
            errors.append((word, str(e)))

    print(f"\n{'─'*60}")
    print(f"Done.  Generated: {generated}  Skipped: {skipped}  Errors: {len(errors)}")
    if errors:
        print("\nFailed words:")
        for w, err in errors:
            print(f"  {w!r}: {err}")


if __name__ == "__main__":
    main()
